### ISSUE TITLE
Request to add support for LOOKUP, VLOOKUP, HLOOKUP

### ISSUE THREAD

**Issue by airburst** [sutoiku/formula.js#37]
Hi,

Great work on the library.  Do you have any plans to add the LOOKUP functions from EXCEL?

Thanks

**Comment by matthewmueller** [comment]
+1 :-)

**Comment by petermoresi** [comment]
You may want to consider these libraries instead:

https://github.com/FormulaPages/lookup
https://github.com/FormulaPages/hlookup
https://github.com/FormulaPages/vlookup

**Comment by airburst** [comment]
Thanks very much; I'll take a look at that library.  Sorry - I haven't had the time to pull and write myself yet.
