### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by hsit18** [sutoiku/formula.js#38]
I want to use [Sourcegraph](https://sourcegraph.com) for formula.js code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/sutoiku/formula.js. (It should only take 30 seconds.)

Thank you!

**Comment by psq** [comment]
well, sourcegraph.com gave a 500 after clicking on the authorize button.  And now https://sourcegraph.com/github.com/sutoiku/formula.js gives a 401...  We'll see if I hear back.

**Comment by psq** [comment]
among other things, the build fails (https://sourcegraph.com/github.com/sutoiku/formula.js/.builds/1719371).
