### ISSUE TITLE
How do i get this to Work

### ISSUE THREAD

**Issue by ScottDWagner** [sutoiku/formula.js#39]
The Documentation is lacking to the point that i am not sure what i need to do to allow this to run on my site. I keep getting the require error. I am sure i need to install something else but if there is more requirements can they please be listed and possibly a simple example would be great. Looks like i need WebPack and Node.JS to get this to run but how would i install it to my project.

**Comment by patrickgamer** [comment]
For starters you don't install NodeJS on your website - have a look at http://nodejs.org for more info.

This module is designed to be included in other larger projects - it's not a drag-and-drop solution for adding some kind of interface to websites. Best to consider it a supporting lib, not an end product.

**Comment by ScottDWagner** [comment]
I am just wanting to use the Excel functions as i am converting a Excel Document to a site. Having the ability to use the same functionality as Excel would be great just calling the functions with the right values helps.I like the fact that it is a supporting lib. just wanting to know what i need to get it up and running on my site. thats all.

**Comment by ScottDWagner** [comment]
I think i have it now. Thank you.
