### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by gnomadic** [sutoiku/formula.js#42]
http://stoic.com/formula 404s.

**Comment by siboulet** [comment]
Also looking for the documentation.

**Comment by mlconnor** [comment]
+1

**Comment by rubenrivera** [comment]
+1

**Comment by maptiger** [comment]
+1

**Comment by fiatjaf** [comment]
http://web.archive.org/web/20130208005916/http://stoic.com/formula

**Comment by Lana345** [comment]
+

**Comment by tonidy** [comment]
Any update on this? Maybe you can use github pages.

**Comment by dsnowdon** [comment]
+1

**Comment by slacie** [comment]
+1

**Comment by nicolashefti** [comment]
Hi,

In case someone reads this old thread, there is a new [documentation website](https://formulajs.info/) and also a community based repo: https://github.com/formulajs/formulajs

Enjoy
