### ISSUE TITLE
formula.js on CDN

### ISSUE THREAD

**Issue by nicolashefti** [sutoiku/formula.js#48]
Hi,

I would like to bring formula.js an hosted CDN repository (for example: https://cdnjs.com or http://www.jsdelivr.com). This might imply some updates of the repository:

- build files included in the repository
- reduce slightly the number of dependencies (maybe include bessel into the code) and let numeral, numeric and jStats as external dependencies.

I am ready to create a pull request in this direction and wonder if would fit the current guidelines of the library development?

Thanks in advance.
Nicolas

**Comment by jalateras** [comment]
@nicolashefti put together a PR and we'll take a look at it.

**Comment by nicolashefti** [comment]
Just made the PR #49
